### ISSUE TITLE
compilation fails on OSX 10.8

### ISSUE THREAD

**Issue by dafyk** [dedis/Dissent#7]
I am trying to compile on OSX 10.8.2 with qt/cryptopp installed from Homebrew.

...
cc1plus: warnings being treated as errors
src/Transports/BufferEdgeListener.cpp: In member function ‘virtual void Dissent::Transports::BufferEdgeListener::OnStart()’:
src/Transports/BufferEdgeListener.cpp:34: warning: suggest a space before ‘;’ or explicit braces around empty body in ‘while’ statement
make: **\* [BufferEdgeListener.o] Error 1

**Comment by davidiw** [comment]
Could you use the suggested solution (a space before the semi-colon at the end of the line) and let me know if that gets rid of the warning?  It appears that this is related to an old gcc warning.  Alternatively, comment out:

QMAKE_CXXFLAGS += -Werror
QMAKE_CFLAGS += -Werror

in dissent.pro and retry.

**Comment by dafyk** [comment]
Editing src/Transports/BufferEdgeListener.cpp line 34 and adding space resolves the problem and compilation ends without warnings or errors, but when i try to run dissent.app i see this error in console (app quits immediately)

com.apple.launchd.peruser.501[269]: ([0x0-0x2ba7ba5].com.yourcompany.dissent[47773]) Exited with code: 255

**Comment by davidiw** [comment]
Ok, I'll make a tweak to the code.

Unfortunately, we have done 0 development on Windows and Mac.  Have you gone through the README?  Did you use a configuration file?  How did you use the application?

**Comment by davidiw** [comment]
Anyway let's open up another issue.  If you could be more descriptive, so that I can help trace the issue.  Note: as of now I have _no_ access to a Mac.  So I am flying blind.

**Comment by dafyk** [comment]
I am not developer and i just wanted to try it :-) Compilation works and binary can be run too but not using dissent.app (like i did) but by running binary located inside "dissent.app/Contents/MacOS/dissent"

:$ ./dissent.app/Contents/MacOS/dissent 
usage: ./dissent.app/Contents/MacOS/dissent [options] [settings.conf]

**Comment by davidiw** [comment]
Cool, I'm glad you got it working.  I made the tweak to the source code so other Mac users can compile it without issue.  Let me know if you make any more progress.
